name: Bar

on:
  repository_dispatch:
    types: [bar-trigger]

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sleep
        run: sleep 30

      - name: Print params
        run: |
          echo "sha: ${{ github.sha }}"
          echo "ref: ${{ github.ref }}"
          echo "date: ${{ github.event.client_payload.date}}"
          echo "val: ${{ github.event.client_payload.val}}"
